M48
; DRILL file {KiCad 9.0.3} date 2025-09-08T16:46:24-0400
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2025-09-08T16:46:24-04:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,9.0.3
; #@! TF.FileFunction,NonPlated,1,4,NPTH
FMAT,2
INCH
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.1181
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C0.1260
%
G90
G05
T1
X6.645Y-3.07
T2
X3.875Y-1.675
X3.875Y-4.0
X6.65Y-1.15
X6.65Y-4.4
M30
